# Generated by Django 3.1 on 2022-12-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20221206_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='work_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peron',
            name='degree_short_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peron',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
