# Generated by Django 3.1 on 2022-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_peron_degree_long_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
