# Generated by Django 3.1 on 2022-12-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20221206_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peron',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='data_base',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='degree_long_form',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='degree_short_form',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='education',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='programming_laung',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='peron',
            name='university',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('perce_of_proficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.peron')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.peron')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laungue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_description', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.peron')),
            ],
        ),
    ]
