# Generated by Django 3.1 on 2022-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20221207_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='peron',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
