# Generated by Django 3.1 on 2022-12-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_peron_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peron',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/resume'),
        ),
    ]
