# Generated by Django 3.1 on 2022-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20221207_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
