# Generated by Django 3.1 on 2022-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_organization_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='completion_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
