# Generated by Django 3.1 on 2022-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
