# Generated by Django 3.1 on 2022-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_auto_20221207_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peron',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
