# Generated by Django 4.1.4 on 2022-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_auto_20221207_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='peron',
            name='qrCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
